# Generated by Django 4.2.7 on 2025-12-04 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assignment_course_homework_studentgroup_testquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
    ]
