# Generated by Django 4.2.7 on 2025-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_grade_grade_value_alter_grade_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='revision_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к доработке'),
        ),
        migrations.AddField(
            model_name='grade',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата запроса доработки'),
        ),
    ]
