# Generated by Django 4.2.7 on 2026-01-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_grade_revision_comment_grade_revision_requested_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='revision_comment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='revision_requested_at',
        ),
    ]
